<#
.SYNOPSIS
    Manifest generator (DECISION-003): contract.index.json -> application-manifest.json.

.DESCRIPTION
    Implements docs/architecture/MANIFEST-GENERATOR.md:
      Input 1: contract.index.json (generated by build-contract-index.ps1, DECISION-001)
      Input 2: source scan (.bas checksums, NumberOfModules/NumberOfFiles, .b4a/.bas
               first lines recorded separately per RULE-SETUP-002/003)
      Input 3: component-provenance.json (library-version, verification-status)
      Input 5: gate evidence write-back - gates entries, immutable GATE-INSTANCE
               nodes, EVIDENCE refs, (gate,scope) counters from .agent/STATE.md
               (traceability sections 5-6: regenerated at every gate attempt,
               never hand-edited, priors retained timestamped).

.PARAMETER AppFolder
    Generated app folder containing contract/, contract.index.json, .bas/.b4a.

.PARAMETER ContractVersion
    Version stamp recorded in the manifest (defaults to the index version).

.PARAMETER Gate
    Gate id (G0..G8) to write back. Requires -GateResult.

.PARAMETER GateResult
    PASS (gate closed) or FAIL (gate open + failure GATE-INSTANCE node).

.PARAMETER Scope
    Scope id of the gate attempt (default: whole-app). E.g. FEATURE-002, SCREEN-001.

.PARAMETER EvidencePath
    Real evidence path recorded as an EVIDENCE node (build log, report, PNG).
    Relative to the app folder or absolute.

.PARAMETER EvidenceType
    Evidence type label (build-log, ux-review, test-result, capture, ...).

.PARAMETER LifecycleState
    Explicit lifecycle-state override (traceability section 5). Otherwise the
    previous manifest state is carried forward (default IMPLEMENTED).

.EXAMPLE
    pwsh -File build-manifest.ps1 -AppFolder C:\b4a\workspace\MyStore -Gate G4 -GateResult PASS -EvidencePath ux-review/BUILD-WATCH-20260911.md -EvidenceType build-log
#>

param(
    [Parameter(Mandatory = $true)][string]$AppFolder,
    [string]$ContractVersion = "",
    [string]$Provenance = "",
    [string]$Gate = "",
    [ValidateSet("", "PASS", "FAIL")][string]$GateResult = "",
    [string]$Scope = "whole-app",
    [string]$EvidencePath = "",
    [string]$EvidenceType = "gate-evidence",
    [string]$LifecycleState = ""
)

$ErrorActionPreference = "Stop"
if ([string]::IsNullOrWhiteSpace($Provenance)) {
    $Provenance = Join-Path $PSScriptRoot "..\..\b4xdaisyuikit\references\component-provenance.json"
}
$contractDir = Join-Path $AppFolder "contract"
if (-not (Test-Path $contractDir)) { Write-Host "FAIL: missing contract/" -ForegroundColor Red; exit 1 }

function ConvertTo-Array($v) {
    $out = @()
    if ($null -ne $v) { if ($v -is [array]) { $out = $v } else { $out = @($v) } }
    return ,$out
}

# --- Input 1: contract.index.json (DECISION-001) ---
$indexFile = Join-Path $AppFolder "contract.index.json"
if (-not (Test-Path $indexFile)) { Write-Host "FAIL: missing contract.index.json - run build-contract-index.ps1 first (DECISION-001)" -ForegroundColor Red; exit 1 }
try { $idx = Get-Content $indexFile -Raw | ConvertFrom-Json } catch { Write-Host ("FAIL: contract.index.json unparseable: " + $_.Exception.Message) -ForegroundColor Red; exit 1 }

if ([string]::IsNullOrWhiteSpace($ContractVersion)) {
    $ContractVersion = if ($idx.application.version) { [string]$idx.application.version } else { "1" }
}
$idxFeatures = ConvertTo-Array $idx.features
$idxScreens  = ConvertTo-Array $idx.screens
$idxTests    = ConvertTo-Array $idx.tests
$idxComps    = ConvertTo-Array $idx.components
$idxEdges    = ConvertTo-Array $idx.edges

# --- Input 3: Level-3 provenance ---
$prov = @{}
$pj = $null
if (Test-Path $Provenance) {
    try { $pj = Get-Content $Provenance -Raw | ConvertFrom-Json; $libVer = $pj.library_version } catch { $pj = $null; $libVer = "" }
    if ($pj -and $pj.components) { foreach ($pn in $pj.components.PSObject.Properties.Name) { $prov[$pn] = $pj.components.$pn } }
} else { $libVer = "" }

# --- Input 2: source scan (checksums + realizes edges, mechanical slug match only) ---
$basFiles = Get-ChildItem -Path $AppFolder -Filter "*.bas" -File -ErrorAction SilentlyContinue | Where-Object { $_.Name -notlike 'B4XDaisy*.bas' }
$mods = @(); $realizeEdges = @()
foreach ($b in $basFiles) {
    $h = [System.Security.Cryptography.SHA256]::Create()
    $bytes = [System.IO.File]::ReadAllBytes($b.FullName)
    $sum = -join ($h.ComputeHash($bytes) | ForEach-Object { $_.ToString("x2") })
    $slug = ($b.BaseName -replace '^B4XPage', '')
    $codeRef = "CODE:$($b.Name)"
    $realizes = @()
    foreach ($s in $idxScreens) {
        if ($slug -and $s.name -and ($s.name -match [regex]::Escape($slug))) {
            $realizes += $codeRef
            $realizeEdges += [pscustomobject]@{ from = $codeRef; type = "realizes"; to = $s.id }
        }
    }
    $mods += [pscustomobject]@{ path = $b.Name; checksum = $sum; last_modified = $b.LastWriteTimeUtc.ToString("o"); realizes = @($realizes | Sort-Object -Unique) }
}
$b4a = Get-ChildItem -Path $AppFolder -Filter "*.b4a" -File -ErrorAction SilentlyContinue | Select-Object -First 1
$build = [pscustomobject]@{ b4a_first_line = ""; bas_first_line = "B4A=true"; NumberOfModules = $basFiles.Count; NumberOfFiles = 0; last_build_status = "unknown"; evidence = "" }
if ($b4a) {
    $build.b4a_first_line = (Get-Content $b4a.FullName -TotalCount 1)
    $mt = Select-String -Path $b4a.FullName -Pattern '^NumberOfModules=(\d+)' | Select-Object -First 1
    if ($mt) { $build | Add-Member -NotePropertyName NumberOfModules_declared -NotePropertyValue ([int]$mt.Matches[0].Groups[1].Value) -Force }
    $mf = Select-String -Path $b4a.FullName -Pattern '^NumberOfFiles=(\d+)' | Select-Object -First 1
    if ($mf) { $build.NumberOfFiles = [int]$mf.Matches[0].Groups[1].Value }
    $fd = Select-String -Path $b4a.FullName -Pattern '^FileN='
    if ($fd) { $build | Add-Member -NotePropertyName FileN_declared -NotePropertyValue @($fd).Count -Force }
}

# --- Input 5: gate evidence write-back (traceability sections 5-6, DECISION-003) ---
$manifestPath = Join-Path $AppFolder "application-manifest.json"
$prev = $null
if (Test-Path $manifestPath) { try { $prev = Get-Content $manifestPath -Raw | ConvertFrom-Json } catch { $prev = $null } }
$now = (Get-Date).ToUniversalTime().ToString("o")

$gates = [ordered]@{}
if ($prev -and $prev.gates) { foreach ($p in $prev.gates.PSObject.Properties) { $gates[$p.Name] = $p.Value } }
$gateInstances = @(); if ($prev -and $prev.'gate-instances') { $gateInstances = ConvertTo-Array $prev.'gate-instances' }
$evidence = @();   if ($prev -and $prev.evidence)   { $evidence   = ConvertTo-Array $prev.evidence }

if ($Gate -ne "" -and $GateResult -ne "") {
    $evRef = ""
    if (-not [string]::IsNullOrWhiteSpace($EvidencePath)) {
        $evRef = "EVIDENCE-{0:D3}" -f (@($evidence).Count + 1)
        $evidence += [pscustomobject]@{ id = $evRef; type = $EvidenceType; path = $EvidencePath; "produced-by-gate" = $Gate }
    }
    # (gate, scope) remediation counters from .agent/STATE.md (GATE-STATE-MACHINE section 3)
    $loopCount = $null
    $stateFile = Join-Path $AppFolder ".agent\STATE.md"
    if (Test-Path $stateFile) {
        $st = Get-Content $stateFile -Raw
        $gBlock = [regex]::Match($st, ('(?ms)^\s*' + [regex]::Escape($Gate) + ':\s*(.*?)(?=^\s*[A-Za-z][\w-]*:|\z)'))
        if ($gBlock.Success) {
            $cMatch = [regex]::Match($gBlock.Groups[1].Value, ('(?m)^\s*' + [regex]::Escape($Scope) + ':\s*(\d+)'))
            if ($cMatch.Success) { $loopCount = [int]$cMatch.Groups[1].Value }
        }
    }
    if ($GateResult -ieq "PASS") {
        $gates[$Gate] = [pscustomobject]@{ status = "closed"; "closed-at" = $now; evidence = $evRef }
    } else {
        $gates[$Gate] = [pscustomobject]@{ status = "open"; evidence = $evRef; "remediation-loop-count" = $loopCount }
    }
    $gateInstances += [pscustomobject]@{ id = "GATE-INSTANCE-{0:D3}" -f (@($gateInstances).Count + 1); gate = $Gate; scope = $Scope; result = $GateResult.ToUpper(); at = $now; evidence = $evRef }
}

# lifecycle-state: param > carried forward from prior manifest > default (traceability section 5)
$lc = $LifecycleState
if ([string]::IsNullOrWhiteSpace($lc) -and $prev -and $prev.application) { $lc = $prev.application.'lifecycle-state' }
if ([string]::IsNullOrWhiteSpace($lc)) { $lc = "IMPLEMENTED" }

# --- assembly (traceability section 5): contract nodes from index, mechanical only ---
$featuresOut = @(); foreach ($ft in $idxFeatures) {
    $featuresOut += [pscustomobject]@{ id = $ft.id; name = $ft.name; status = $ft.status; implements = (ConvertTo-Array $ft.implements); screens = (ConvertTo-Array $ft.screens); rules = (ConvertTo-Array $ft.rules) }
}
$screensOut = @(); foreach ($s in $idxScreens) {
    $codeForScreen = @($realizeEdges | Where-Object { $_.to -eq $s.id } | ForEach-Object { $_.from } | Sort-Object -Unique)
    $screensOut += [pscustomobject]@{ id = $s.id; name = $s.name; feature = $s.feature; components = (ConvertTo-Array $s.components); tests = (ConvertTo-Array $s.tests); navigation_in = (ConvertTo-Array $s.navigation_in); navigation_out = (ConvertTo-Array $s.navigation_out); code = $codeForScreen; status = $s.status }
}
$testsOut = @(); foreach ($t in $idxTests) {
    $lastRun = ""; $lastRes = "not-run"; $lastEv = ""
    if ($prev -and $prev.tests) {
        $pt = @($prev.tests) | Where-Object { $_.id -eq $t.id } | Select-Object -First 1
        if ($pt) { $lastRun = $pt.'last-run'; $lastRes = $pt.result; $lastEv = $pt.evidence }
    }
    $testsOut += [pscustomobject]@{ id = $t.id; verifies = (ConvertTo-Array $t.verifies); "last-run" = $lastRun; result = $lastRes; evidence = $lastEv }
}
$compsOut = @(); foreach ($c in $idxComps) {
    $cn = ($c.id -replace '^COMPONENT-', '')
    $pv = $prov[$cn]
    $usedBy = @(@($idxScreens) | Where-Object { @($_.components) -contains $c.id } | ForEach-Object { $_.id })
    $compsOut += [pscustomobject]@{ id = $c.id; library_version = if ($pv) { $pv.'library-version' } else { $libVer }; verification_status = if ($pv) { $pv.'api-verification-status' } else { "unknown" }; used_by = @($usedBy) }
}
$allEdges = @(@($idxEdges) + @($realizeEdges))

$manifest = [ordered]@{
    application = [ordered]@{ id = "app-$((Split-Path $AppFolder -Leaf).ToLower())"; name = (Split-Path $AppFolder -Leaf)
        contract_version = $ContractVersion; lifecycle_state = $lc
        generated_at = $now; generator_version = "build-manifest.ps1 v2.0" }
    features = @($featuresOut); screens = @($screensOut)
    components = @($compsOut)
    source_modules = @($mods)
    tests = @($testsOut); build = $build; gates = $gates; "gate-instances" = @($gateInstances); evidence = @($evidence); edges = @($allEdges)
}
$ts = Get-Date -Format "yyyyMMdd-HHmmss"
$out = Join-Path $AppFolder "application-manifest.json"
$manifest | ConvertTo-Json -Depth 10 | Set-Content $out -Encoding UTF8
Copy-Item $out (Join-Path $AppFolder "application-manifest.$ts.json") -Force
Write-Host "Wrote $out (gates: $(@($gates.Keys) -join ', ')) (+ timestamped prior)" -ForegroundColor Green
exit 0
